set_target:
    description: Set target temperature.
    fields:
        entity_id:
            description: Name of the recteq switch entity
            example: "switch.smoker"
        temperature:
            description: Target temperature in °F
            example: "275"
